FROM python:3.13-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip \
 && pip install -r requirements.txt

COPY log_config.toml .
COPY src/custom_formatter.py .
COPY src/mcp_server_weibo ./mcp_server_weibo

VOLUME ["/app/logs"]

ENV PYTHONPATH=/app

EXPOSE 4200

CMD ["python", "-m", "mcp_server_weibo.server", "http"]
